name: Install Bombsite and check
run-name: ${{ github.actor }} - Bombsite
on: [push]
jobs:
  Install-Bombsite-And-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Bombsite
        run: |
          python -m pip install -r requirements-dev.txt -e .
      - name: Run Pylint
        run: |
          python -m pylint --rcfile=.settings/pylintrc src/
